# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-venky"
BBFILE_PATTERN_meta-venky = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-venky = "6"

LAYERDEPENDS_meta-venky = "core"
LAYERSERIES_COMPAT_meta-venky = "scarthgap"
